#!/bin/bash

sudo apt-get -y update
sudo apt-get install python3.7
sudo apt-get install -y python-pip
sudo apt-get install -y python-software-properties 
sudo apt-get install -y build-essential
sudo apt-get install -y libpq-dev
sudo apt-get install -y libxml2-dev libxslt-dev  python-dev  python-setuptools
sudo python setup.py install
