#!/bin/bash

apt-get -y update
apt-get install python3.7
apt-get install -y python-pip
apt-get install -y python-software-properties 
apt-get install -y build-essential
apt-get install -y libpq-dev
apt-get install -y libxml2-dev libxslt-dev  python-dev  python-setuptools
python3 setup.py install
